# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/terraform',
                'doc_host': 'https://rpetrov.github.io',
                'git_url': 'https://github.com/rpetrov/terraform',
                'lib_path': 'terraform'},
  'syms': {'terraform.core': {'terraform.core.foo': ('core.html#foo', 'terraform/core.py')}}}
